AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a VPC"

Parameters:
  CidrBlock:
    Description: The CIDR Block of the VPC
    Default: "10.0.0.0/24"
    
Resources:

  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref CidrBlock